// <auto-generated />
namespace PersistenceLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class relationshipMistakesCorrection0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationshipMistakesCorrection0));
        
        string IMigrationMetadata.Id
        {
            get { return "202002190706559_relationshipMistakesCorrection0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
