// <auto-generated />
namespace PersistenceLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class sectionContent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sectionContent));
        
        string IMigrationMetadata.Id
        {
            get { return "202002181656404_sectionContent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
